FROM golang:1.24-alpine AS builder

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .

RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o gateway-service ./cmd/gateway-service

FROM alpine:3.20

WORKDIR /app

COPY --from=builder /app/gateway-service .

ENV GATEWAY_PORT=8080

EXPOSE 8080

CMD ["./gateway-service"]